### ISSUE TITLE
if/elif/else

### ISSUE THREAD

**Issue by lucarin91** [PisaCoderDojo/cpython-ita#1]
non riusciamo a farlo funzionare

**Comment by matteobusi** [comment]
Leggendo i commenti in Grammar/Grammar sembra che la maggiorparte delle modifiche fatte lì debbano riflettersi su Modules/parsermodule.c 
Imho in [parsermodule.c:1190](https://github.com/PisaCoderDojo/cpython-ita/blob/master/Modules/parsermodule.c#L1190) c'è il motivo per cui il se/senno/altrimenti non funziona.

**Comment by lucarin91** [comment]
mi sa proprio di si... ti vuoi occupare di questo problema?

**Comment by matteobusi** [comment]
Se non avete troppa fretta una sera, penso di poter risolvere

**Comment by andreamad8** [comment]
Fixed in 9d62f2846abdd0b771c31b0c090ed87d34d81ab7
