### ISSUE TITLE
Vero/Falso

### ISSUE THREAD

**Issue by lucarin91** [PisaCoderDojo/cpython-ita#2]
trovare un modo per cambiare True e False in Vero e Falso

**Comment by AntonioCarta** [comment]
secondo me si potrebbe creare un modulo in cui ridefinire tutte le funzioni standard, da importare automaticamente all'avvio dell'interprete.
Il modulo avra definizioni del tipo:

```
Vero = True
Falso = False
stampa = print
```

per caricare il modulo si potrebbe usare l'opzione -m dell'interprete python chiamando
`python -m modulo_ita`

**Comment by lucarin91** [comment]
considerando che stiamo facendo una vesion custom di cpython direi che sarebbe meglio aggiungere `stampa` tra le funzioni della libreria standard invece di caricarla rxternamente.

Invece per quanto riguarda Vero/Falso preferirei risolverli dal parser, anche se forse non cambia poi molto... non lo sò da ragionare

**Comment by AntonioCarta** [comment]
Certo, quella è la soluzione più pulita, il problema è che non sappiamo quanto va modificato il parser a causa di queste piccole modifiche alla grammatica. Io lo limiterei ai costrutti indispensabili per semplificare.

Per le funzioni di libreria tu intendi proprio rinominare le funzioni della libreria standard?

**Comment by lucarin91** [comment]
> Per le funzioni di libreria tu intendi proprio rinominare le funzioni della libreria standard?

si, in qualche modo prima di far partirre l'interpretazione python definisce la funzione print, noi ci mettiamo lì e definiamo anche la nostra stampa.

**Comment by lucarin91** [comment]
f865d846580f345c92c5f70d0a6d9320c28d5fc1
